[advisories]
unmaintained = "workspace"

ignore = [
    "RUSTSEC-2021-0145"
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]

[bans]
multiple-versions = "deny"
wildcards = "warn"
skip = [
    { name = "hermit-abi" },
    { name = "unicode-width" },
    { name = "syn" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
